import { getCheckLoanExtendLimit } from "@services/api/loan";
import React from "react";
import { SvgProps } from "react-native-svg";

const icons: Record<string, React.FC<SvgProps>> = {
  renew_button: require("@assets/images/renew_button.svg").default,
  changepin: require("@assets/images/changepin.svg").default,
  upload: require("@assets/images/upload.svg").default,
  trash: require("@assets/images/trash.svg").default,
  mainupload: require("@assets/images/mainupload.svg").default,
  carloanheader: require("@assets/images/carloanheader.svg").default,
  pencil: require("@assets/images/pencil.svg").default,
  bluearrow: require("@assets/images/blueslider.svg").default,
  carloancheck: require("@assets/images/carloancheck.svg").default,
  caruploadcheck: require("@assets/images/caruploadcheck.svg").default,
  carloading: require("@assets/images/caruploadloading.svg").default,
  branchpin: require("@assets/images/branch_pin.svg").default,
  arrow_right: require("@assets/images/arrow_right.svg").default,
  notf_active: require("@assets/images/notf_active.svg").default,
  notf_read: require("@assets/images/notf_read.svg").default,
  statement_upload_car: require("@assets/images/statement_upload_car.svg")
    .default,
  statement_upload_deposit:
    require("@assets/images/statement_upload_deposit.svg").default,
  get_loan_header: require("@assets/images/get_loan_header.svg").default,
  loancard_request_arrow: require("@assets/images/loancard_request_arrow.svg")
    .default,
  get_loan_header_car: require("@assets/images/get_loan_header_car.svg")
    .default,
  get_loan_header_deposit: require("@assets/images/get_loan_header_deposit.svg")
    .default,
  get_loan_header_phone: require("@assets/images/get_loan_header_phone.svg")
    .default,
  loanlist_icon: require("@assets/images/loanlist_icon.svg").default,
  loanlist_icon_car: require("@assets/images/loanlist_icon_car.svg").default,
  loanlist_icon_deposit: require("@assets/images/loanlist_icon_deposit.svg")
    .default,
  loanlist_icon_phone: require("@assets/images/loanlist_icon_phone.svg")
    .default,
  loanlist_car: require("@assets/images/loanlist_car.svg").default,
  back: require("@assets/images/onboardingback.svg").default,
  getbutton: require("@assets/images/getbutton.svg").default,
  rand_icon: require("@assets/images/rand_icon.svg").default,
  month_slider: require("@assets/images/month_slider.svg").default,
  onboarding_next: require("@assets/images/onboardingbutton.svg").default,
  loancard_left: require("@assets/images/loancard_icon.svg").default,
  loancard_arrow: require("@assets/images/loancard_arrow.svg").default,
  archive: require("@assets/images/archive.svg").default,
  calculator: require("@assets/images/calculator.svg").default,
  faq: require("@assets/images/faq.svg").default,
  check_circle: require("@assets/images/check_circle").default,
  inv_friend: require("@assets/images/inv_friend.svg").default,
  location: require("@assets/images/location.svg").default,
  terms: require("@assets/images/terms.svg").default,
  operator: require("@assets/images/operator.svg").default,
  menu: require("@assets/images/menu.svg").default,
  home: require("@assets/images/home.svg").default,
  no_loan: require("@assets/images/no_loan.svg").default,
  bonus: require("@assets/images/bonus.svg").default,
  personal_inf: require("@assets/images/personal_inf.svg").default,
  bank_add: require("@assets/images/add_icon.svg").default,
  contact_set: require("@assets/images/contact_set.svg").default,
  login_menu: require("@assets/images/login_menu.svg").default,
  login_operator: require("@assets/images/login_operator.svg").default,
  login_fb: require("@assets/images/login_fb.svg").default,
  login_loc: require("@assets/images/login_loc.svg").default,
  login_set: require("@assets/images/login_set.svg").default,
  houseloading: require("@assets/images/houseloading.svg").default,
  reg_bank: require("@assets/images/reg_bank.svg").default,
  houseupload: require("@assets/images/houseupload.svg").default,
  pass_icon: require("@assets/images/pass.svg").default,
  reject_icon: require("@assets/images/reject.svg").default,
  yellowarrow: require("@assets/images/yellowarrow.svg").default,
  settings_user: require("@assets/images/settings_user.svg").default,
  settings_arrow: require("@assets/images/purple_arrow.svg").default,
  houseloanheader: require("@assets/images/houseloanheader.svg").default,
  branch_pin: require("@assets/images/branch_pin.svg").default,
  branch_pin_car: require("@assets/images/branch_pin_car.svg").default,
  branch_schedule: require("@assets/images/branch_schedule.svg").default,
  branch_schedule_car: require("@assets/images/branch_schedule_car.svg")
    .default,
  arrowright: require("@assets/images/arrowright.svg").default,
  contract_check: require("@assets/images/contract_check.svg").default,
  contract_check_active: require("@assets/images/contract_check_active.svg")
    .default,
  depositloancard: require("@assets/images/depositloancard.svg").default,
  remove_signature: require("@assets/images/signature_remove.svg").default,
  mashaan: require("@assets/images/car.svg").default,
  warning: require("@assets/images/warning.svg").default,
  stepper_current: require("@assets/images/stepper_current.svg").default,
  stepper_done: require("@assets/images/stepper_done.svg").default,
  change_pass: require("@assets/images/change_pass.svg").default,

  change_phone: require("@assets/images/change_phone.svg").default,
  stop: require("@assets/images/stop.svg").default,
  change_email: require("@assets/images/change_email.svg").default,

  auth_hidepass: require("@assets/images/auth_hidepass.svg").default,
  auth_showpass: require("@assets/images/auth_showpass.svg").default,
  copy: require("@assets/images/copy.svg").default,
  faceid: require("@assets/images/faceid.svg").default,
  fingerprint: require("@assets/images/fingerprint.svg").default,
  loan_graphic: require("@assets/images/loan_graphic.svg").default,
  loan_collateral: require("@assets/images/loan_collateral.svg").default,
  loan_transaction: require("@assets/images/loan_transaction.svg").default,
  selfie_camera: require("@assets/images/selfie_camera.svg").default,
  avatar: require("@assets/images/avatar.svg").default,
  payment_edit: require("@assets/images/payment_edit.svg").default,
  login_icon: require("@assets/images/login_icon.svg").default,
  slider_car: require("@assets/images/slider_car.svg").default,
  slider: require("@assets/images/slider.svg").default,
  slider_deposit: require("@assets/images/slider_deposit.svg").default,
  slider_phone: require("@assets/images/slider_phone.svg").default,
  laon_confirm_check: require("@assets/images/laon_confirm_check.svg").default,
  get_loan_branch_pin: require("@assets/images/get_loan_branch_pin.svg")
    .default,
  success_loan_request: require("@assets/images/success_loan_request.svg")
    .default,
  getloan_detail_select: require("@assets/images/getloan_detail_select.svg")
    .default,
  getloan_detail_bank_empty:
    require("@assets/images/getloan_detail_bank_empty.svg").default,
  getloan_detail_branch_empty:
    require("@assets/images/getloan_detail_branch_empty.svg").default,
  getloan_detail_contact_empty:
    require("@assets/images/getloan_detail_contact_empty.svg").default,
  getloan_detail_select_deposit:
    require("@assets/images/getloan_detail_select_deposit.svg").default,
  getloan_detail_select_phone:
    require("@assets/images/getloan_detail_select_phone.svg").default,
  active_loan_request: require("@assets/images/active_loan_request.svg")
    .default,
  request_status_inactive: require("@assets/images/request_status_inactive.svg")
    .default,
  request_status_active_deposit:
    require("@assets/images/request_status_active_deposit.svg").default,
  request_status_active_car:
    require("@assets/images/request_statuc_active_car.svg").default,
  request_status_active_phone:
    require("@assets/images/request_status_active_phone.svg").default,
  qpay_arrow: require("@assets/images/qpay_arrow.svg").default,
  loan_card_deposit: require("@assets/images/loan_card_deposit.svg").default,
  loan_card_phone: require("@assets/images/loan_card_phone.svg").default,
  loan_card_car: require("@assets/images/loan_card_car.svg").default,
  loan_card_digital: require("@assets/images/loan_card_digital.svg").default,
  request_list: require("@assets/images/request_list.svg").default,
  arrow_deposit: require("@assets/images/arrow_deposit.svg").default,
  arrow_phone: require("@assets/images/arrow_phone.svg").default,
  arrow_car: require("@assets/images/arrow_car.svg").default,
  login_help_arrow: require("@assets/images/login_help_arrow.svg").default,
  onboard1: require("@assets/images/onbrdicon1.svg").default,
  onboard2: require("@assets/images/onbrdicon2.svg").default,
  onboard3: require("@assets/images/onbrdicon3.svg").default,
  onbrdarrow: require("@assets/images/onbrdarrow.svg").default,
  onboardimg1: require("@assets/images/onboardimg1.svg").default,
  loancardicon: require("@assets/images/loancardicon.svg").default,
  exit: require("@assets/images/exit.svg").default,
  friends: require("@assets/images/friends.svg").default,
  trust: require("@assets/images/trust.svg").default,
  notification: require("@assets/images/notification.svg").default,
  phone: require("@assets/images/phone.svg").default,
  password: require("@assets/images/password.svg").default,
  extend: require("@assets/images/extend.svg").default,
  graphic: require("@assets/images/graphic.svg").default,
  deposit: require("@assets/images/deposit.svg").default,
  history: require("@assets/images/history.svg").default,
  facebook: require("@assets/images/facebook.svg").default,
  email: require("@assets/images/email.svg").default,
  envelope: require("@assets/images/envelope.svg").default,
  invite_friend: require("@assets/images/invite_friend.svg").default,
  my_info: require("@assets/images/my_inf.svg").default,
  arrow_up: require("@assets/images/arrow_up.svg").default,
  my_inf: require("@assets/images/my_info.svg").default,
  phone2: require("@assets/images/phone2.svg").default,
  hide: require("@assets/images/settings_showpass.svg").default,
  show: require("@assets/images/settings_hidepass.svg").default,
  chard: require("@assets/images/chard.svg").default,
  normal: require("@assets/images/pass.svg").default,
  branch_phone: require("@assets/images/branch_phone.svg").default,
  exceeded: require("@assets/images/reject.svg").default,
  receipt: require("@assets/images/receipt.svg").default,
  market: require("@assets/images/market.svg").default,
  noti_bell: require("@assets/images/bell.svg").default,
  faq_corner: require("@assets/images/faq_corner.svg").default,
  header_back: require("@assets/images/headerback.svg").default,
  phone_outline: require("@assets/images/edit_link.svg").default,
  edit_link: require("@assets/images/phone_outline.svg").default,
};

export default icons;
